// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afqabhxtwmupapkhzryl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmcWFiaHh0d211cGFwa2h6cnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDg1NzgsImV4cCI6MjA2NjQyNDU3OH0.OaqSzj0p-yyBKltp4ia1XYOaMKjzvznU2k1ncCRwU6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);